---
# tasks file for bvansomeren.openvpn-freebsd-server

- name: include install
  include: install.yml

- name: include configure
  include: configure.yml

- name: include server keys
  include: server-keys.yml

- name: include client key generation
  include: client-configs.yml 
